<a href="https://colab.research.google.com/github/Nutsudapenpong/DPDM/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #ไลบราลี่สำหรับคำนวณ

In [2]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
A.T #Transpose matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
A.dot(A.T) #คูณเมทริกซ์

array([[14, 32],
       [32, 77]])

In [6]:
A #ขนาดไม่ได้

ValueError: ignored

## Array slicing

In [7]:
A[0,1] #ชี้จุดว่าค่าเป็นเท่าไร

2

In [8]:
A[:,:2] #ข้างหน้าคือแถว ข้างหลังคือหลัก ตัอย่างแถวเอาทั้งหมด หลักเอาแค่ถึง 2

array([[1, 2],
       [4, 5]])

In [10]:
A[1,1:]

array([5, 6])

###Distance matrix (Manhattan)

In [11]:
A = np.array([[1,2],[3,5],[2,0],[4,5]])
A

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [12]:
def Manhattan_dist(dp1,dp2):
    distX = abs(dp1[0]-dp2[0])
    distY = abs(dp1[1]-dp2[1])
    return distX + distY

In [13]:
np.zeros((4,4)) #ข้อมูลมี 4 เมทริกซ์ระยะห่างก็จะมี 4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((4,4)) #สร้างอาเรย์เปล่า

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
7*np.ones((4,4))

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [16]:
dist_mat_man = np.zeros((4,4))
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
for i in range(4):
    for j in range(4):
        dist_mat_man[i,j] = Manhattan_dist(A[i,:],A[j,:])

dist_mat_man

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

#HW 6
สร้าง Distance metrix (Euclidean) ของ data matrix ใน slides
โดยสร้าง function สำหรับคำนวณ Euclidean Distance