<a href="https://colab.research.google.com/github/Nutsudapenpong/DPDM/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np #ไลบราลี่สำหรับคำนวณ

In [22]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
A.T #Transpose matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
A.dot(A.T) #คูณเมทริกซ์

array([[14, 32],
       [32, 77]])

In [26]:
A #ขนาดไม่ได้

array([[1, 2, 3],
       [4, 5, 6]])

## Array slicing

In [27]:
A[0,1] #ชี้จุดว่าค่าเป็นเท่าไร

2

In [28]:
A[:,:2] #ข้างหน้าคือแถว ข้างหลังคือหลัก ตัอย่างแถวเอาทั้งหมด หลักเอาแค่ถึง 2

array([[1, 2],
       [4, 5]])

In [29]:
A[1,1:]

array([5, 6])

###Distance matrix (Manhattan)

In [30]:
A = np.array([[1,2],[3,5],[2,0],[4,5]])
A

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [31]:
def Manhattan_dist(dp1,dp2):
    distX = abs(dp1[0]-dp2[0])
    distY = abs(dp1[1]-dp2[1])
    return distX + distY

In [32]:
np.zeros((4,4)) #ข้อมูลมี 4 เมทริกซ์ระยะห่างก็จะมี 4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((4,4)) #สร้างอาเรย์เปล่า

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
7*np.ones((4,4))

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [35]:
dist_mat_man = np.zeros((4,4))
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
for i in range(4):
    for j in range(4):
        dist_mat_man[i,j] = Manhattan_dist(A[i,:],A[j,:])

dist_mat_man

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

#HW 6
สร้าง Distance metrix (Euclidean) ของ data matrix ใน slides
โดยสร้าง function สำหรับคำนวณ Euclidean Distance

In [37]:
B = np.array([[1,2],[3,5],[2,0],[4,5]])
B

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [38]:
def Euclidean_dist(dp1,dp2):
    distX = (dp1[0]-dp2[0])**2
    distY = (dp1[1]-dp2[1])**2
    return (distX + distY)**(0.5)

In [39]:
dist_Euclidean = np.zeros((4,4))
dist_Euclidean

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
for i in range(4):
    for j in range(4):
        dist_Euclidean[i,j] = Euclidean_dist(B[i,:],B[j,:])

dist_Euclidean

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

## Distance of nominal or categorical features

(extra) Python data structure (Dictionary)


In [43]:
d_A = {'a':1,2:3,3:5,'cat':6} #ตัวเลขหน้าเป็นค่า ตัวเลขหลังเป็น Index
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [45]:
{2: 3, 3: 5, 'a':1, 'cat': 6} #
d_A['cat']

6

In [47]:
d_A['dog' ]= [1,2,3,4,5]
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [48]:
del d_A[2]
d_A

{3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [49]:
import pandas as pd

In [50]:
data_dict = {'color':['red','red','green'], #color = {'red', 'green', 'blue'}
                   'status':['single', 'married', 'single']} #status ={single', 'married', 'divorced'}
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

In [52]:
data_pd = pd.DataFrame.from_dict(data_dict)
data_pd

color   status
0    red   single
1    red  married
2  green   single

# Categorical feature distance method#1





In [53]:
list(data_pd.iloc[1,:]) 

['red', 'married']

In [64]:
def meth1_dist(data1,data2):
     N = 0
     print(f' data1 is {data1} and data2 is {data2}')
     for i in range(len(data1)):
          print(f' feature{i} of data1 is {data1[i]} , feature{i} of data2 is {data2[i]} ' )
          if data1[i]  !=  data2[i]:
               N = N+1
               print(f'     {data1[i]} is not equal {data2[i]} : updated ({N}) ' )
          else:
               print(f'     {data1[i]} is equal {data2[i]} ' )
     return N/len(data1)

In [65]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

 data1 is ['red', 'single'] and data2 is ['red', 'married']
 feature0 of data1 is red , feature0 of data2 is red 
     red is equal red 
 feature1 of data1 is single , feature1 of data2 is married 
     single is not equal married : updated (1) 


0.5

### HW7 calculate distance matrix of data_pd using meth1_dist()

In [71]:
dist_Meth1 = np.zeros((3,3))
dist_Meth1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
for i in range(3):
    for j in range(3):
        dist_Meth1[i,j] = meth1_dist(list(data_pd.iloc[i,:]),list(data_pd.iloc[j,:]))

dist_Meth1

 data1 is ['red', 'single'] and data2 is ['red', 'single']
 feature0 of data1 is red , feature0 of data2 is red 
     red is equal red 
 feature1 of data1 is single , feature1 of data2 is single 
     single is equal single 
 data1 is ['red', 'single'] and data2 is ['red', 'married']
 feature0 of data1 is red , feature0 of data2 is red 
     red is equal red 
 feature1 of data1 is single , feature1 of data2 is married 
     single is not equal married : updated (1) 
 data1 is ['red', 'single'] and data2 is ['green', 'single']
 feature0 of data1 is red , feature0 of data2 is green 
     red is not equal green : updated (1) 
 feature1 of data1 is single , feature1 of data2 is single 
     single is equal single 
 data1 is ['red', 'married'] and data2 is ['red', 'single']
 feature0 of data1 is red , feature0 of data2 is red 
     red is equal red 
 feature1 of data1 is married , feature1 of data2 is single 
     married is not equal single : updated (1) 
 data1 is ['red', 'married'] and d

array([[0. , 0.5, 0.5],
       [0.5, 0. , 1. ],
       [0.5, 1. , 0. ]])

## Categorical feature distance method#2

In [80]:
data_dict2 = {'color':['red','red','green','blue'], #color = {'red', 'green', 'blue'}
                   'status':['single', 'married', 'single','divorced']} #status ={single', 'married', 'divorced'}
data_pd2 = pd.DataFrame.from_dict(data_dict2)
data_pd2

color    status
0    red    single
1    red   married
2  green    single
3   blue  divorced

In [81]:
data_pd_binary = pd.get_dummies(data_pd2)
data_pd_binary = data_pd_binary.iloc[:3,:]
data_pd_binary

color_blue  color_green  ...  status_married  status_single
0           0            0  ...               0              1
1           0            0  ...               1              0
2           0            1  ...               0              1

[3 rows x 6 columns]

In [83]:
def binary_sym_dist(data1,data2): 
      r = 0
      s = 0
      t = 0
      q = 0
      for i in range(len(data1)):
          print(f' feature{i} of data1 is {data1[i]} , feature{i} of data2 is {data2[i]} ' )
          if data1[i]  !=  data2[i]:
               if data1[i] == 0:
                   s = s + 1
               else: 
                   r = r + 1
          else:
                if data1[i] == 0:
                   t = t + 1
                else:
                   q = q + 1
               
      return (r+s)/(r+s+t+q)

In [85]:
binary_sym_dist(list(data_pd_binary.iloc[0,:]),list(data_pd_binary.iloc[1,:]))

 feature0 of data1 is 0 , feature0 of data2 is 0 
 feature1 of data1 is 0 , feature1 of data2 is 0 
 feature2 of data1 is 1 , feature2 of data2 is 1 
 feature3 of data1 is 0 , feature3 of data2 is 0 
 feature4 of data1 is 0 , feature4 of data2 is 1 
 feature5 of data1 is 1 , feature5 of data2 is 0 


0.3333333333333333

### HW8 calculate distance matrix of data_pd_binary using binary_sym_dist()

In [86]:
dist_binary_sym = np.zeros((3,3)) #สร้างเมทริกซ์มารองรับค่าที่จะได้
dist_binary_sym

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
for i in range(3):   #เติมค่าระยะห่าง
    for j in range(3): 
        dist_binary_sym[i,j] = binary_sym_dist(list(data_pd_binary.iloc[i,:]),list(data_pd_binary.iloc[j,:]))

dist_binary_sym

 feature0 of data1 is 0 , feature0 of data2 is 0 
 feature1 of data1 is 0 , feature1 of data2 is 0 
 feature2 of data1 is 1 , feature2 of data2 is 1 
 feature3 of data1 is 0 , feature3 of data2 is 0 
 feature4 of data1 is 0 , feature4 of data2 is 0 
 feature5 of data1 is 1 , feature5 of data2 is 1 
 feature0 of data1 is 0 , feature0 of data2 is 0 
 feature1 of data1 is 0 , feature1 of data2 is 0 
 feature2 of data1 is 1 , feature2 of data2 is 1 
 feature3 of data1 is 0 , feature3 of data2 is 0 
 feature4 of data1 is 0 , feature4 of data2 is 1 
 feature5 of data1 is 1 , feature5 of data2 is 0 
 feature0 of data1 is 0 , feature0 of data2 is 0 
 feature1 of data1 is 0 , feature1 of data2 is 1 
 feature2 of data1 is 1 , feature2 of data2 is 0 
 feature3 of data1 is 0 , feature3 of data2 is 0 
 feature4 of data1 is 0 , feature4 of data2 is 0 
 feature5 of data1 is 1 , feature5 of data2 is 1 
 feature0 of data1 is 0 , feature0 of data2 is 0 
 feature1 of data1 is 0 , feature1 of data2 is 0 


array([[0.        , 0.33333333, 0.33333333],
       [0.33333333, 0.        , 0.66666667],
       [0.33333333, 0.66666667, 0.        ]])