<a href="https://colab.research.google.com/github/Nutsudapenpong/DPDM/blob/master/odinplusyolov5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/New_yolo

/content/drive/MyDrive/New_yolo


In [ ]:
!python main.py --nn densenet10 --out_dataset Imagenet --magnitude 0.0014 --temperature 1000 --gpu 0

python3: can't open file 'main.py': [Errno 2] No such file or directory


In [3]:
%cd yolov5

/content/drive/MyDrive/New_yolo/yolov5


In [4]:
cd ..

/content/drive/MyDrive/New_yolo


In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
import tensorflow as tf
tf.test.gpu_device_name()

''

In [4]:
!python yolov5/detect.py --source mydatasets/testaddout/images --weights yolov5/runs/train/exp6/weights/best.pt --conf-thres 0.5 --iou-thres 0.45

detect: weights=['yolov5/runs/train/exp6/weights/best.pt'], source=mydatasets/testaddout/images, data=yolov5/data/coco128.yaml, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=yolov5/runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 v6.1-177-gd059d1d torch 1.11.0+cu113 CUDA:0 (Tesla T4, 15110MiB)

Processing in-distribution images
Fusing layers... 
Model summary: 476 layers, 76164816 parameters, 0 gradients
tensor([-2.95344, -2.19522, -2.67024, -2.28199, -2.03955, -1.74455, -3.25994])
1
[   0.076931     0.16421     0.10212     0.15056     0.19187      0.2577    0.056622]
0.25770044
2
[    0.14279     0.14289     0.14283     0.14288     0.14292     0.14296     0.14274]
0.14295784
tensor([-3.57475, -2.54593, -2.38052, -1.5848

In [ ]:
import torch 
import tensorflow as tf

p = torch.tensor([1,6])
t = torch.tensor([2,3])
z = torch.tensor([[]])
z = torch.cat([([p,t])],0)
print(z)

TypeError: ignored